### ISSUE TITLE
[FEATURE] 코드 정리

### ISSUE THREAD

**Issue by sena-22** [sena-22/stack-overflow-clone#2]
### Describe the required feature
- 코드 정리

### Todo
- [x] 미사용 코드 및 패키지 제거
- [x] 주석 정리
- [x] 컴포넌트 스타일 통일
- [x] 코드 스타일 적용(esling, prettier)
